import type { Product, ProductImage } from "./types";

type ProductInput = Omit<Product, "gallery"> & {
  galleryImages?: Array<{ src: string; position?: string }>;
};

function defineProduct(input: ProductInput): Product {
  const { galleryImages, ...product } = input;
  const gallerySources = galleryImages ?? [
    { src: product.image, position: product.imagePosition },
    { src: product.hoverImage },
    { src: "/images/padma-rose.jpg" },
  ];
  const gallery: ProductImage[] = gallerySources.map((image, index) => ({
    ...image,
    alt: `${product.name} — view ${index + 1}`,
  }));
  return { ...product, gallery };
}

export const products: Product[] = [
  defineProduct({
    id: "neelambari-silk-saree",
    name: "Neelambari Silk Saree",
    category: "Sarees",
    price: 8990,
    originalPrice: 10990,
    image: "/images/padma-ivory.jpg",
    hoverImage: "/images/padma-hero.webp",
    galleryImages: [
      { src: "/images/padma-ivory.jpg", position: "50% 48%" },
      { src: "/images/padma-hero.webp", position: "50% 34%" },
      { src: "/images/padma-sage.jpg", position: "50% 38%" },
      { src: "/images/padma-rose.jpg", position: "50% 36%" },
    ],
    badge: "Bestseller",
    colors: ["Indigo", "Rani Pink"],
    sizes: ["Free Size"],
    description: "Handwoven silk with an antique zari border.",
    material: "Pure handwoven silk with antique zari",
    features: ["Handwoven by artisan partners", "Antique zari border", "Lightweight festive drape", "Finished with hand-tied tassels"],
    care: "Dry clean only. Store folded in muslin and air periodically.",
    included: "Saree with an unstitched blouse piece",
    origin: "Crafted in Varanasi, India",
    deliveryEstimate: "4–7 business days",
    sku: "PAD-SAR-NEE-01",
    imagePosition: "50% 48%",
  }),
  defineProduct({
    id: "gulmohar-kurta-set",
    name: "Gulmohar Kurta Set",
    category: "Kurta Sets",
    price: 5490,
    image: "/images/padma-sage.jpg",
    hoverImage: "/images/padma-rose.jpg",
    badge: "New",
    colors: ["Emerald", "Sindoor"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    description: "A luminous three-piece set with hand-finished details.",
    material: "Cotton-silk kurta with organza dupatta",
    features: ["Three-piece coordinated set", "Hand-finished neckline", "Side pockets", "Soft cotton lining"],
    care: "Gentle dry clean recommended. Steam on low heat.",
    included: "Kurta, tapered trousers and organza dupatta",
    origin: "Crafted in Jaipur, India",
    deliveryEstimate: "5–8 business days",
    sku: "PAD-KRT-GUL-02",
    imagePosition: "50% 38%",
  }),
  defineProduct({
    id: "surya-embroidered-kaftan",
    name: "Surya Embroidered Kaftan",
    category: "Co-ords",
    price: 4290,
    originalPrice: 4990,
    image: "/images/padma-rose.jpg",
    hoverImage: "/images/padma-sage.jpg",
    badge: "Limited",
    colors: ["Marigold"],
    sizes: ["S", "M", "L", "XL"],
    description: "Fluid cotton-silk, embroidered in joyful florals.",
    material: "Breathable cotton-silk blend",
    features: ["Relaxed kaftan silhouette", "Artisanal floral embroidery", "Concealed side pockets", "Soft lustrous finish"],
    care: "Dry clean or gentle hand wash separately in cold water.",
    included: "Embroidered kaftan dress",
    origin: "Crafted in Lucknow, India",
    deliveryEstimate: "4–7 business days",
    sku: "PAD-COO-SUR-03",
    imagePosition: "50% 35%",
  }),
  defineProduct({
    id: "kumudini-festive-lehenga",
    name: "Kumudini Festive Lehenga",
    category: "Lehengas",
    price: 12990,
    image: "/images/padma-hero.webp",
    hoverImage: "/images/padma-ivory.jpg",
    colors: ["Jamun", "Antique Gold"],
    sizes: ["XS", "S", "M", "L", "XL"],
    description: "A statement silhouette made for evening celebrations.",
    material: "Silk-blend brocade with cotton lining",
    features: ["Panelled festive skirt", "Adjustable waist fastening", "Hand-embroidered blouse", "Lightweight woven dupatta"],
    care: "Dry clean only. Store each piece separately in muslin.",
    included: "Lehenga, blouse and dupatta",
    origin: "Crafted in Mumbai, India",
    deliveryEstimate: "7–10 business days",
    sku: "PAD-LEH-KUM-04",
    imagePosition: "54% 50%",
  }),
  defineProduct({
    id: "rasa-drape-saree",
    name: "Rasa Drape Saree",
    category: "Sarees",
    price: 6990,
    image: "/images/padma-hero.webp",
    hoverImage: "/images/padma-ivory.jpg",
    badge: "Padma Edit",
    colors: ["Plum", "Gold"],
    sizes: ["S", "M", "L", "XL"],
    description: "An effortless pre-drape with a traditional soul.",
    material: "Fluid crepe with woven zari accents",
    features: ["Ready-to-wear pre-drape", "Adjustable inner waistband", "Statement zari pallu", "Easy movement and fall"],
    care: "Dry clean only. Hang briefly before wear to release folds.",
    included: "Pre-draped saree and stitched blouse",
    origin: "Crafted in Surat, India",
    deliveryEstimate: "5–8 business days",
    sku: "PAD-SAR-RAS-05",
    imagePosition: "50% 34%",
  }),
  defineProduct({
    id: "vasant-cotton-set",
    name: "Vasant Cotton Set",
    category: "Kurta Sets",
    price: 3890,
    image: "/images/padma-rose.jpg",
    hoverImage: "/images/padma-sage.jpg",
    colors: ["Haldi", "Gulabi"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    description: "Everyday ease in breathable embroidered cotton.",
    material: "100% breathable cotton",
    features: ["Two-piece everyday set", "Delicate thread embroidery", "Side pockets", "Relaxed straight fit"],
    care: "Gentle machine wash cold with similar colours. Line dry.",
    included: "Kurta and straight trousers",
    origin: "Crafted in Jaipur, India",
    deliveryEstimate: "3–6 business days",
    sku: "PAD-KRT-VAS-06",
    imagePosition: "50% 42%",
  }),
  defineProduct({
    id: "meher-brocade-lehenga",
    name: "Meher Brocade Lehenga",
    category: "Lehengas",
    price: 15990,
    originalPrice: 17990,
    image: "/images/padma-ivory.jpg",
    hoverImage: "/images/padma-hero.webp",
    badge: "Occasion",
    colors: ["Royal Blue", "Silver"],
    sizes: ["XS", "S", "M", "L", "XL"],
    description: "Heritage brocade balanced by a modern, lighter form.",
    material: "Silk brocade with breathable cotton lining",
    features: ["Heritage woven brocade", "Contoured blouse", "Generous flare", "Soft net dupatta"],
    care: "Specialist dry clean only. Avoid direct perfume on zari.",
    included: "Brocade lehenga, blouse and dupatta",
    origin: "Crafted in Varanasi, India",
    deliveryEstimate: "7–10 business days",
    sku: "PAD-LEH-MEH-07",
    imagePosition: "42% 50%",
  }),
  defineProduct({
    id: "aamra-co-ord-set",
    name: "Aamra Co-ord Set",
    category: "Co-ords",
    price: 4790,
    image: "/images/padma-sage.jpg",
    hoverImage: "/images/padma-rose.jpg",
    badge: "New",
    colors: ["Mehendi", "Ivory"],
    sizes: ["XS", "S", "M", "L", "XL"],
    description: "Contemporary separates alive with artisanal print.",
    material: "Cotton-linen blend with artisanal print",
    features: ["Relaxed longline top", "Elasticated trouser back", "Functional pockets", "Mix-and-match separates"],
    care: "Gentle hand wash in cold water. Dry in shade.",
    included: "Printed top and wide-leg trousers",
    origin: "Crafted in Ahmedabad, India",
    deliveryEstimate: "4–7 business days",
    sku: "PAD-COO-AAM-08",
    imagePosition: "50% 45%",
  }),
];

export function getProductById(id: string) {
  return products.find((product) => product.id === id);
}
